import { FC, PropsWithChildren } from 'react';
import Head from 'next/head';

import styles from './Main.module.css';
import { Navbar } from '../Navbar';

export const MainLayout: FC<PropsWithChildren<unknown>> = ({ children }) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>{`Intro NextJS -  `}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />

			<main className={styles.main}>{children}</main>
		</div>
	);
};
